set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED True)
set(CMAKE_AUTOMOC ON)
if (${CMAKE_BUILD_TYPE} STREQUAL "Debug")
    add_compile_definitions(GF_TIME_FEATURE_DETECT)
    add_compile_definitions(GF_TIME_FEATURE_MATCH)
    add_compile_definitions(GF_TIME_FEATURE_DESCRIPTOR)
    add_compile_definitions(GF_LOG_KEYPOINT)
    add_compile_definitions(GF_LOG_DESCRIPTOR)
    add_compile_definitions(GF_LOG_MATCH)
    add_compile_definitions(GF_LOG_FRONTEND)
endif ()