macro(VIO_SLAM SLAM_SRC)
    file(GLOB_RECURSE Sensor_SRC ${PROJECT_SOURCE_DIR}/src/Sensors/*.*)
    file(GLOB_RECURSE UI_SRC ${PROJECT_SOURCE_DIR}/src/QtUI/*.*)
    file(GLOB_RECURSE Util_SRC ${PROJECT_SOURCE_DIR}/src/Util/*.*)
    file(GLOB_RECURSE S_SRC ${PROJECT_SOURCE_DIR}/src/SLAM/*.*)
    file(GLOB_RECURSE EVAL_SRC ${PROJECT_SOURCE_DIR}/src/Evaluation/*.*)
    file(GLOB_RECURSE CONF_SRC ${PROJECT_SOURCE_DIR}/src/ConfMap/*.*)
    file(GLOB QRC_SRC ${PROJECT_SOURCE_DIR}/res/*.qrc)
    list(APPEND SLAM_SRC ${Sensor_SRC} ${UI_SRC} ${Util_SRC} ${S_SRC}
            ${EVAL_SRC} ${CONF_SRC} ${QRC_SRC})
endmacro()
VIO_SLAM(SLAM_SRC)
